### PR TITLE
P2081: Rebase the LFTS on C++20

### PR DESCRIPTION
**Pull request by tkoeppe**
@Dani-Hub, @mclow, @CaseyCarter: Would any of you like to review this motion application?

### CODE REVIEW

**Comment by Dani-Hub** [comment]
I volunteer to review a final (html) document of that pull request, but I guess I can get this only after the pull has been done, right?

**Comment by tkoeppe** [comment]
@Dani-Hub: the tip of this branch includes the up-to-date HTML, "fundamentals-ts.html". Does that work for you?

(The Part 1 and Part 2 commits don't update the HTML, but I can trivially add that if that'd be helpful!)

**Comment by tkoeppe** [comment]
Note 1 to self/selves: When we applied http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0052r10.pdf way back when, we actually had to backport that paper from C++20 "mandates" language to C++17, because the paper was written against the IS, not the TS. It is worth revisiting that paper to see if our rebasing edits have succeeded at undoing that backport!

Note 2 to self: Some ugly instances of "_Preconditions_: `p != nullptr`." remain; I would prefer those to say "`p` is not null.".

Note 3 to editor: you still need to rearrange the elements to bring them into canonical order. To be done after this has been merged.

**Comment by tkoeppe** [comment]
@Dani-Hub: And thank you so much!

**Pull request merged**
